version: '3.7'

services:
  db:
    image: postgres:12-alpine
    environment:
      POSTGRES_DB: advance_auth
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - 5432:5432
